#!/bin/sh
. /usr/sup/use/use.sh
use comp40
for i in midmark.um sandmark.umz 
do
  /usr/bin/time -f "um $i: %U seconds (user time)" ./um $i > /dev/null
done
/usr/bin/time -f "um advent.umz: %U seconds (user time)" \
./um advent.umz < sol.txt > /dev/null